BACKBONE:
  gray: true
  layerToDiscard: 0
  model:
    class: customModels.resnet18_features
    params:
      weights: DEFAULT
DATASET:
  class: customDatasets.OMITomoSlices
  params:
    label_files:
    - normal.txt
    - malignant.txt
    root: /super-ssd/Cantone/datasets/OMIDB.tomo.SlicesPNG.cropped/
    slices: 'lambda n: np.linspace(0, n-1, 11, dtype=int)'
DATA_TRANSFORM:
- class: customTransform.ToTensorFloat32
  params: {}
- class: torchvision.transforms.Resize
  params:
    antialias: true
    size:
    - 1024
    - 512
- class: customTransform.MinMax
  params: {}
MODEL:
  class: customModels.SoftAttn_slice
  params:
    img_size:
    - 1024
    - 512
    num_classes: 2
TARGET_TRANSFORM:
- class: customTransform.OneHot
  params:
    num_classes: 2
TRAINING:
  device: cuda:3
  resume: False
  epochs: 45
  num_workers: 15
  parallel:  null
  split_seed: 44
  workspace: /home/dellascenza/results/OMIDB/task-mal-nonmal/softonly/resnet18/run-9_seed-44/
